addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

language: php
php:
  - 7.1
  - 7.2

env:
  matrix:
  - MAGENTO_VERSION=2.2
  - MAGENTO_VERSION=2.3

before_install:
  - git clone --depth=50 --branch=$MAGENTO_VERSION https://github.com/magento/magento2.git /tmp/magento
  - mysql -uroot -e 'SET @@global.sql_mode = NO_ENGINE_SUBSTITUTION; CREATE DATABASE magento_integration_tests;'
  - mv /tmp/magento/dev/tests/integration/etc/install-config-mysql.travis.php.dist /tmp/magento/dev/tests/integration/etc/install-config-mysql.php
  - mkdir -p /tmp/magento/app/code/Firegento
  - cp -R $(pwd) /tmp/magento/app/code/Firegento/ContentProvisioning

install:
  - cd /tmp/magento
  - composer install --no-interaction

script:
  - php /tmp/magento/vendor/bin/phpunit -c /tmp/magento/app/code/Firegento/ContentProvisioning/Test/Integration/phpunit.travis.xml
